usr_dashboard:
    resource: "@UsrDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

usr_admin:
    resource: "@UsrAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

usr_user:
    resource: "@UsrUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
