parameters:
#    parameter_name: value

services:
    usr_user.registration_complet:
        class: Usr\UserBundle\EventListener\RegistrationSuccessListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }