check_full_register:
    path: /register-confirm
    defaults: { _controller: UsrUserBundle:Default:index }

usr_user_homepage:
    path:     /
    defaults: { _controller: UsrUserBundle:Default:index }
