role_selector:
    path: /user-type
    defaults: { _controller: UsrUserBundle:Default:roleselector }

check_full_register:
    path: /register-confirm
    defaults: { _controller: UsrUserBundle:Default:registerconfirm }

usr_user_homepage:
    path:     /
    defaults: { _controller: UsrUserBundle:Default:index }

fos_user_registration_success:
    path: /register-form
    defaults: { _controller: UsrUserBundle:Registration:registercuccess}