services:
    usr_user.orm.validator.unique:
            class: Usr\UserBundle\Validator\Constraints\UniqueEntityValidator
            arguments: [ "@doctrine" ]
            tags:
                - { name: validator.constraint_validator, alias: rocket.orm.validator.unique }